=== ivanramoss-safa/DAW2/DocumentosDAW1/Lenguaje de Marca/xml/xml+dtd/piratas.dtd
<!ELEMENT piratas (biblioteca)>
<!ELEMENT biblioteca (libro+)>
<!ELEMENT libro (titulo, autor, fechaPublicacion)>
<!ELEMENT titulo (#PCDATA)>

<!ELEMENT autor (#PCDATA)>
<!ATTLIST autor fechaNacimiento CDATA #IMPLIED>

<!ELEMENT fechaPublicacion EMPTY>
<!ATTLIST fechaPublicacion aÃ±o CDATA #REQUIRED>

=== ivanramoss-safa/DAW2/DocumentosDAW1/Lenguaje de Marca/xml/xml+dtd/piratas.xml
<?xml version='1.0' encoding="UTF-8"?>

<!DOCTYPE personas SYSTEM "../xml+dtd/piratas.dtd">

<piratas>
    <biblioteca>
        <libro>
            <titulo>La vida está en otra parte</titulo>
            <autor>Milian Kundera</autor>
            <fechaPublicacion año="1973"></fechaPublicacion>
        </libro>
        <libro>
            <titulo>Pantaleón y las visitadoras</titulo>
            <autor fechaNacimiento="28/03/1936">Mario Vargas Llosa</autor>
            <fechaPublicacion año="1973"></fechaPublicacion>
        </libro>
        <libro>
            <titulo>Conversación en la catedral</titulo>
            <autor fechaNacimiento="28/03/1936">Mario Vargas Llosa</autor>
            <fechaPublicacion año="1969"></fechaPublicacion>
        </libro>
    </biblioteca>
</piratas>
