=== ivanramoss-safa/DAW2/DocumentosDAW1/Lenguaje de Marca/xml/xml+dtd+schema+xslt/pokedex.dtd
<!ELEMENT pokedex (pokemon)>

<!ELEMENT pokemon (datos_generales, tipologia, stats_base, evoluciones)>
<!ATTLIST pokemon
    nombre CDATA #REQUIRED
    num_pokedex CDATA #REQUIRED>

<!ELEMENT datos_generales (altura, peso, sexo, categoria, habilidad)>
<!ELEMENT altura (#PCDATA)>
<!ELEMENT peso (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT habilidad (#PCDATA)>

<!ELEMENT tipologia (tipos, debilidades)>
<!ELEMENT tipos (tipo)>
<!ELEMENT tipo (descripci贸n)>
<!ELEMENT descripci贸n (#PCDATA)>
<!ELEMENT debilidades (debilidad)>
<!ELEMENT debilidad (tipo, efectividad)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT efectividad (#PCDATA)>

<!ELEMENT stats_base (ps, at, def, spat, spde, vel)>
<!ELEMENT ps (#PCDATA)>
<!ELEMENT at (#PCDATA)>
<!ELEMENT def (#PCDATA)>
<!ELEMENT spat (#PCDATA)>
<!ELEMENT spde (#PCDATA)>
<!ELEMENT vel (#PCDATA)>

<!ELEMENT evoluciones (evoluci贸n)>
<!ELEMENT evoluci贸n (orden, num_pokedex)>
<!ELEMENT orden (#PCDATA)>
<!ELEMENT num_pokedex (#PCDATA)>

=== ivanramoss-safa/DAW2/DocumentosDAW1/Lenguaje de Marca/xml/xml+dtd+schema+xslt/pokedex.xml
<?xml version='1.0' encoding="UTF-8"?>

<!DOCTYPE pokedex SYSTEM "../xml+dtd+schema/pokedex.dtd">
<?xml-stylesheet href="pokedex.xslt" type="text/xsl"?>

<pokedex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation="pokedex.xsd">
    <pokemon nombre="bulbasur" num_pokedex="1" url_imagen="https://static.wikia.nocookie.net/espokemon/images/4/43/Bulbasaur.png">
        <datos_generales>
            <altura>0.45</altura>
            <peso>20</peso>
            <sexo>M|F</sexo>
            <categoria>Semilla</categoria>
            <habilidad>Espesura</habilidad>
        </datos_generales>
        <tipologia>
            <tipos>
                <tipo>
                    <descripci贸n>planta</descripci贸n>
                </tipo>
            </tipos>
            <debilidades>
                <debilidad>
                    <tipo>fuego</tipo>
                    <efectividad>x2</efectividad>
                </debilidad>
                <debilidad>
                    <tipo>volador</tipo>
                    <efectividad>x2</efectividad>
                </debilidad>
            </debilidades>
            <fortalezas>
                <fortaleza>
                    <tipo>Agua</tipo>
                    <efectividad>x2</efectividad>
                </fortaleza>
                <fortaleza>
                    <tipo>Tierra</tipo>
                    <efectividad>x2</efectividad>
                </fortaleza>
            </fortalezas>
        </tipologia>
        <stats_base>
            <ps>30</ps>
            <at>10</at>
            <def>12</def>
            <spat>15</spat>
            <spde>13</spde>
            <vel>5</vel>
        </stats_base>
        <evoluciones>
            <evoluci贸n>
                <orden>-1</orden>
                <num_pokedex>2</num_pokedex>
            </evoluci贸n>
        </evoluciones>
    </pokemon>
</pokedex>
